# Generated by Django 5.2.7 on 2025-10-16 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaConstelar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Un título o enfoque para la constelación (ej: 'Mi relación con el dinero').", max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Notas o intenciones del cliente sobre este sistema.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('configuracion_visual_json', models.JSONField(blank=True, help_text='Datos JSON con las posiciones, colores y enlaces del diagrama.', null=True)),
                ('cliente', models.ForeignKey(help_text='Usuario (cliente) que creó esta constelación.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del elemento (ej: 'Mamá', 'La Casa', 'Mi Miedo').", max_length=100)),
                ('tipo', models.CharField(choices=[('PER', 'Persona/Familiar'), ('OBJ', 'Objeto/Lugar'), ('CON', "Concepto/Sentimiento (ej: 'Culpa', 'Éxito')")], default='PER', help_text='Define si es una persona, objeto o concepto.', max_length=3)),
                ('rol', models.CharField(blank=True, help_text="Rol o cualidad asignada por el cliente (ej: 'El Excluido', 'Lo Inaccesible').", max_length=150)),
                ('notas', models.TextField(blank=True, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='constelacion.sistemaconstelar')),
            ],
        ),
    ]
